import * as vscode from "vscode";
import { Recipe } from "./providers/chat";

export function askRepoLensCommand(
  recipes: Recipe[],
  contextRange?: vscode.Range
) {
  showAskRepoLensQuickPick(recipes).then((result: any) => {
    let message;
    if ("id" in result) {
      // the user selected a specific recipe
      message = {
        target: "languageServer",
        view: "chat",
        request: "executeRecipe",
        recipeId: result.id,
        name: result.label,
        trigger: "askRepoLens",
      };
    } else {
      // the user entered some custom text
      message = {
        target: "languageServer",
        view: "chat",
        request: "sendMessage",
        textContent: result.label,
      };
    }

    // Open the chat window.
    // This command is automatically generated by the extension based on the
    // views in the package.json file. It's used here to make sure that the
    // chat window opens after we've "Ask[ed] RepoLens" for something.
    vscode.commands.executeCommand("repolens.chat.focus");

    vscode.commands.executeCommand("repolens.coding_assistant", {
      message,
      ideState: {
        selectionLocation: {
          range: contextRange,
        },
      },
    });
  });
}

export function showAskRepoLensQuickPick(recipes: Recipe[]) {
  return new Promise((resolve) => {
    const recipeNames = recipes.map((item) => item.name);
    const recipeItems = recipes.map((item) => ({
      label: item.name,
      id: item.id,
    }));

    const quickPick = vscode.window.createQuickPick();
    quickPick.placeholder =
      "Ask RepoLens a question or choose one of these recipes";
    quickPick.items = recipeItems;

    quickPick.onDidAccept(() => {
      const selection = quickPick.activeItems[0];
      resolve(selection);
      quickPick.hide();
    });

    quickPick.onDidChangeValue(() => {
      // add what the user has typed to the pick list as the first item
      if (!recipeNames.includes(quickPick.value)) {
        const newItems = [{ label: quickPick.value }, ...recipeItems];
        quickPick.items = newItems;
      }
    });
    quickPick.onDidHide(() => quickPick.dispose());
    quickPick.show();
  });
}
